/*
******************************************************************************
File:		main.c
Info:		Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-03-12
Author:		Ku, Do Yeou
******************************************************************************
*/
			/**
			 * Sensor message structure:
			 * 	- <sensor id>','<counterI>'.'<counterII>','<measurements>'\n'
			 * 	- <sensor id>','<counterI>'.'<counterII>',''unkwn\n'
			 */

#include "main.h"

/* Private defines -----------------------------------------------------------*/
#define SYSTEM_LOG_DELAY_COUNT	5

/* Static functions ----------------------------------------------------------*/
void SystemClock_Config(void);
/* Public functions ----------------------------------------------------------*/
int main(void)
{
	division_line = RESET;

	/* Initialize LEDs : Off */
	led_initialize();

	/* Initialize FATFS */
	FATFS file_system;
	FIL file_pointer;
	FRESULT f_err_code = FR_OK;
	UINT bytes_written;

	file_flag.log_enabled = 0;
	file_flag.file_opened = 0;
	file_flag.filename_ok = PASS;
	SD_FlagStatus SDStatus = 0;

	char filename[13] = "sens3.bin\0";
	char dummy [] = "end";

	do {
		SDStatus = check_memory (
				&file_system,
				&file_pointer,
				f_err_code);
	} while(SDStatus != SD_CARD_OK);

	/* Initialize time stamp */
	timestamp_initialize();
	timestamp_enable();

	/* Initialize Sensors */
	sensor_initialize();

	Sensor_ConfigTypeDef SensorConfig;
	Sensor_StatusTypeDef SensorStatus;
	SensorConfig.accel_rate		=	ACC_PMU_ODR_1000;
	SensorConfig.accel_range	=	ACC_PMU_RANGE_16;
	SensorConfig.gyro_rate		=	GYRO_ODR_1000;
	SensorConfig.gyro_range		=	GYRO_RANGE_RANGE_2000;
	SensorConfig.mag_rate		=	MAG_PWR_CR2_ODR_20;
	SensorConfig.mag_range_xy	=	MAG_REP_XY_HIGH_ACCURACY_PRESET_REPXY;
	SensorConfig.mag_range_z	=	MAG_REP_Z_HIGH_ACCURACY_PRESET_REPZ;

	do{
		SensorStatus = sensor_check_id();
	}while (SensorStatus != SENS_OK);

	do{
		SensorStatus	=	sensor_configure(&SensorConfig);
	}while (SensorStatus != SENS_OK);

	/* Indicate end of sensor initialization */
	Led3_On();

	/* Initialize GNSS */
	gnss_initialize();

	/* Initialize EXTI */
	exti_initialize();

	/* Indicate end of gnss + system initialization */
	Led6_On();

	/* ReInit time_stamp */
	time_stamp.clk_1Hz 		= 0;
	time_stamp.clk_10kHz 	= 0;
	file_flag.log_enabled 	= 1;

	/* Data logging loop */
	while((file_flag.log_enabled == 1))
	{
		if ((volatile int) gnss_log_on == SET)
		{
			Led5_On();
			SDStatus = write_to_memory (
					&file_system,
					&file_pointer,
					f_err_code,
					filename,
					&bytes_written,
					(char*) GNSS_LOG_Buffer,
					gnss_length,
					&file_flag);
			gnss_log_on = RESET;
			Led5_Off();
		}
		if(division_line == SET)
		{
			char message[] = "\n Above epoch is the 5s division line. \n.";
			SDStatus = write_to_memory (
					&file_system,
					&file_pointer,
					f_err_code,
					filename,
					&bytes_written,
					(char*) message,
					(UINT) sizeof(message),
					&file_flag);
			division_line = RESET;
		}
		if ((volatile uint8_t) sensor_log_start != 0xff)
		{
			Led4_On();
			SDStatus = write_to_memory (
					&file_system,
					&file_pointer,
					f_err_code,
					filename,
					&bytes_written,
					(char*) sensor_buffer[sensor_log_start],
					SENSOR_LOG_BUFFER_SIZE,
					&file_flag);

			if(sensor_log_start == (sensor_crnt_buffer + (SENSOR_BUFFER_NUMBER-1))%SENSOR_BUFFER_NUMBER)
			{
				sensor_log_start = 0xff;
				sensor_log_wait = 0;
			}
			else
			{
				sensor_log_start = (sensor_log_start+1)%SENSOR_BUFFER_NUMBER;
				sensor_log_wait--;
			}
			Led4_Off();
		}
	}
	if (file_flag.log_enabled == 0)
	{
		SDStatus = write_to_memory (
				&file_system,
				&file_pointer,
				f_err_code,
				filename,
				&bytes_written,
				dummy,
				sizeof(dummy),
				&file_flag);
	}

	exti_deinitialize();
	Led3_Off();
	Led4_On();
	Led5_On();
	Led6_Off();

	/* Infinite loop */
	while(1)
	{

	}
	return 0;
}
